# example netlify.toml
[build]
  command = "yarn build"
  publish = "dist/client/"

[functions]
  directory = "functions/"

[[redirects]]
   from = "/api/*"
   to = "/.netlify/functions/index"
   status = 200

# [dev]
#   command = "yarn serve" # Command to start your dev server
#   functions = "functions/"
#   targetPort = 5173
#   port = 3000 # Port that the dev server will be listening on
#   publish = "dist/client" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
